name: VHDL Test with GHDL

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GHDL and GTKWave
        run: |
          sudo apt update
          sudo apt install -y ghdl gtkwave

      - name: Compile VHDL files
        run: |
          ghdl -a adder.vhd adder_testbench.vhd
          ghdl -e adder_tb

